// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Individual metric definitions
type CpuMetric struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UsagePercentage float64                `protobuf:"fixed64,2,opt,name=usage_percentage,json=usagePercentage,proto3" json:"usage_percentage,omitempty"` // Range: 0.0 to 100.0
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CpuMetric) Reset() {
	*x = CpuMetric{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetric) ProtoMessage() {}

func (x *CpuMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetric.ProtoReflect.Descriptor instead.
func (*CpuMetric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *CpuMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CpuMetric) GetUsagePercentage() float64 {
	if x != nil {
		return x.UsagePercentage
	}
	return 0
}

type RamMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RamMetric) Reset() {
	*x = RamMetric{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RamMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RamMetric) ProtoMessage() {}

func (x *RamMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RamMetric.ProtoReflect.Descriptor instead.
func (*RamMetric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *RamMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RamMetric) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *RamMetric) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

// Wrapper payload to allow streaming various metric types over a single stream
type StreamMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Metric:
	//
	//	*StreamMetricsRequest_Cpu
	//	*StreamMetricsRequest_Ram
	Metric        isStreamMetricsRequest_Metric `protobuf_oneof:"metric"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *StreamMetricsRequest) GetMetric() isStreamMetricsRequest_Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *StreamMetricsRequest) GetCpu() *CpuMetric {
	if x != nil {
		if x, ok := x.Metric.(*StreamMetricsRequest_Cpu); ok {
			return x.Cpu
		}
	}
	return nil
}

func (x *StreamMetricsRequest) GetRam() *RamMetric {
	if x != nil {
		if x, ok := x.Metric.(*StreamMetricsRequest_Ram); ok {
			return x.Ram
		}
	}
	return nil
}

type isStreamMetricsRequest_Metric interface {
	isStreamMetricsRequest_Metric()
}

type StreamMetricsRequest_Cpu struct {
	Cpu *CpuMetric `protobuf:"bytes,1,opt,name=cpu,proto3,oneof"`
}

type StreamMetricsRequest_Ram struct {
	Ram *RamMetric `protobuf:"bytes,2,opt,name=ram,proto3,oneof"`
}

func (*StreamMetricsRequest_Cpu) isStreamMetricsRequest_Metric() {}

func (*StreamMetricsRequest_Ram) isStreamMetricsRequest_Metric() {}

type StreamMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsResponse) Reset() {
	*x = StreamMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsResponse) ProtoMessage() {}

func (x *StreamMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsResponse.ProtoReflect.Descriptor instead.
func (*StreamMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\tCpuMetric\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x10usage_percentage\x18\x02 \x01(\x01R\x0fusagePercentage\"\x85\x01\n" +
	"\tRamMetric\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\"l\n" +
	"\x14StreamMetricsRequest\x12$\n" +
	"\x03cpu\x18\x01 \x01(\v2\x10.proto.CpuMetricH\x00R\x03cpu\x12$\n" +
	"\x03ram\x18\x02 \x01(\v2\x10.proto.RamMetricH\x00R\x03ramB\b\n" +
	"\x06metric\"K\n" +
	"\x15StreamMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2]\n" +
	"\rMetricService\x12L\n" +
	"\rStreamMetrics\x12\x1b.proto.StreamMetricsRequest\x1a\x1c.proto.StreamMetricsResponse(\x01B2Z0andreabarchietto.it/oss/go/Telemetry_Agent/protob\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metrics_proto_goTypes = []any{
	(*CpuMetric)(nil),             // 0: proto.CpuMetric
	(*RamMetric)(nil),             // 1: proto.RamMetric
	(*StreamMetricsRequest)(nil),  // 2: proto.StreamMetricsRequest
	(*StreamMetricsResponse)(nil), // 3: proto.StreamMetricsResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	4, // 0: proto.CpuMetric.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: proto.RamMetric.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: proto.StreamMetricsRequest.cpu:type_name -> proto.CpuMetric
	1, // 3: proto.StreamMetricsRequest.ram:type_name -> proto.RamMetric
	2, // 4: proto.MetricService.StreamMetrics:input_type -> proto.StreamMetricsRequest
	3, // 5: proto.MetricService.StreamMetrics:output_type -> proto.StreamMetricsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_metrics_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamMetricsRequest_Cpu)(nil),
		(*StreamMetricsRequest_Ram)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
